### ISSUE TITLE
Did you support Sequelize ? 

### ISSUE THREAD

**Issue by Afondevi** [mpashkovskiy/express-oas-generator#103]
Hello,

I work with Sequelize ORM.
I manage to generate router, but no request.Body and response.

Thanks for help :)

**Comment by maxiejbe** [comment]
Hi @Afondevi,

The generation of the **endpoint** docs does not depend on the ORM, but in your incoming requests/responses. 
You can check this issue first to check why the docs are not generated: https://github.com/mpashkovskiy/express-oas-generator/issues/94

The disclaimer is that you won't get your models documented with Sequelize. For now the models generation is done only with Mongoose.

Let me know if that works.
Best,

**Comment by Afondevi** [comment]
Hi, Thanks but not understand your reponse.
I get no response and no response status documented, but I use `return next()` on middleware.
I really don't understand how it works ^^'

**Comment by maxiejbe** [comment]
@Afondevi Please take a look at this comment: https://github.com/mpashkovskiy/express-oas-generator/issues/94#issuecomment-857118588

The library does not automagically document based on routes. You have to call the endpoint ("Try it out" in swagger, http clients like Postman, calling from a frontent, executing tests). Then it parses the request and the response, resulting in documenting the input/output.

Let me know if that helps.

**Comment by mpashkovskiy** [comment]
Closing the issue. Feel free to reopen if there are still questions.
