### ISSUE TITLE
[NodeJs16] DeprecationWarning: Invalid 'main' field

### ISSUE THREAD

**Issue by vivaslj1** [mpashkovskiy/express-oas-generator#109]
Hi,
Since Nodejs 16 I am getting following 

DeprecationWarning: Invalid 'main' field in '/Users/vivaslj1/Projects/angie/angie-backend/node_modules/swagger-ui-express/package.json' of './lib/index.js'. Please either fix that or report it to the module author

i've seen the swagger-ui-express@4.3.0 is solved. https://github.com/scottie1984/swagger-ui-express/issues/277
If i instal this dependency, after i get

DeprecationWarning: Invalid 'main' field in '/Users/vivaslj1/Projects/angie/angie-backend/node_modules/express-oas-generator/node_modules/swagger-ui-express/package.json' of './lib/index.js'

Could you please fix that?
Thank you!
Jose

**Comment by Erik-Schlegel** [comment]
I get the same issue. Easy fix from my perspective is to remove the 'main' key from node_modules/swagger-ui-express/package.json

**Comment by mpashkovskiy** [comment]
[Just updated](https://github.com/mpashkovskiy/express-oas-generator/commit/0aa717f1f0cb72b007ba9a796432bbb6b7e7aef3) swagger-ui-express to ^4.4.0. Use express-oas-generator@1.0.41

**Comment by mpashkovskiy** [comment]
Correction: use express-oas-generator@1.0.44
