### ISSUE TITLE
Is it possible to convert express request and response typescript definitions to openapi models?

### ISSUE THREAD

**Issue by jamesone** [mpashkovskiy/express-oas-generator#112]
If I pass the following express route handler, is it possible to convert the req/res typescript types into OAS specs?

```
farmRouter.get(
  '/restroute',
async (
    req: Request<{ field1: string }, any, any, any>,
    res: Response<{ mycustomresponse: string },
      { x: string }
    >,
```

**Comment by mpashkovskiy** [comment]
It is not, unfortunately. The module only sniffs network requests/responses to build the models, not the source code.

**Comment by mannutech** [comment]
The swagger documentation being generated doesn't consists of any Request types or Response types.

How do I make auto-generation to also render Models @mpashkovskiy ?
