### ISSUE TITLE
URL auto conversion issue

### ISSUE THREAD

**Issue by msmohandg** [mpashkovskiy/express-oas-generator#115]
My URL looks like following 

`localhost:80/api/1.0/users`

Auto converter converts like following

`localhost:80/api/1/0/users`

adding extra slash in the dot. How can I fix it?

**Comment by mpashkovskiy** [comment]
Failing to reproduce, see https://github.com/mpashkovskiy/express-oas-generator/tree/fix/dot-in-path branch. Do I miss something? Could you retry and if the issue still exists reopen the ticket with more details?
