### ISSUE TITLE
Function's parameters description

### ISSUE THREAD

**Issue by matheusborguete** [mpashkovskiy/express-oas-generator#13]
Hello! 
First I'd like to congratulate you for your good work with this project!
And here we go: I actually can't manage to show in the Swagger's UI the description of each parameter... Is there specific way of do it? 

Thank you in advance!

**Comment by mpashkovskiy** [comment]
Hi Matheus! I will add an example to develop branch soon and let you know.

**Comment by matheusborguete** [comment]
Nice!

**Comment by mpashkovskiy** [comment]
So here is an example (see develop branch server.js file). You can define a method as a second parameter when you call init (server.js:7) and set description there (server.js:8).

To run the exampe:
* run `node server.js`
* go to `http://localhost:8080/foo/asd` in browser
* and then open Swagger UI `http://localhost:8080/api-docs/`

Hope that answers your question.

**Comment by mpashkovskiy** [comment]
I hope that solved the problem so I'm closing the issue. Let me know if you need any help.

**Comment by matheusborguete** [comment]
I had no time to check you answer in time, sorry. I'm gonna try it until tomorrow and let you know, thanks!

**Comment by matheusborguete** [comment]
Nice, it works perfectly! Thank you!
