### ISSUE TITLE
How to add detail of documentation (description, defenition, etc) for each endpoint

### ISSUE THREAD

**Issue by tommirp** [mpashkovskiy/express-oas-generator#14]
How to add detail of documentation (description, defenition, etc) for each endpoint ?
And how to implement "Try out" functionality of each endpoint?

This is so good! but i still have problem to complete the interactive api-docs.
Thanks

**Comment by mpashkovskiy** [comment]
Hi Tommi
If you check out develop branch there is server.js file.
- run `node server.js`;
- go to http://localhost:8080/api-docs;
- you should see 'Try it out' buttons on right side.

As for descriptions: there are two options:
- you can define those in the code see line 8 from `server.js`;
- you can write Swager spec containing only names and descriptions and provide it as a second argument to init functions. Something like that:
```javascript
const jsonWithNamesAndDescriptions = ... read JSON from file here ...;
expressOasGenerator.init(app, jsonWithNamesAndDescriptions);
```

**Comment by mpashkovskiy** [comment]
I hope my answer helped you. Closing the ticket.
If you need anything else let me know.
