### ISSUE TITLE
Doesn't get body params

### ISSUE THREAD

**Issue by Vnavega** [mpashkovskiy/express-oas-generator#17]
At least I don't know how to do it.
Your work is great! Saved a lot of time for my documentation, but the API request body params.
I use postman to run tests.

**Comment by mpashkovskiy** [comment]
Do you have compression enabled in your app? There is a check for 'content-encoding' header: https://github.com/mpashkovskiy/express-oas-generator/blob/master/lib/processors.js#L151

**Comment by mpashkovskiy** [comment]
Difficult question. Can I somehow reproduce it? Could you share how you configure routes in the app? Maybe you can put a breakpoint somewhere here https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L164 and see why it doesn't end up in `processBody(req, method);`?

**Comment by mpashkovskiy** [comment]
BTW I did some fixes could you try version 1.0.3?

**Comment by Vnavega** [comment]
Oh, really sorry for not answering earlier! 
I'll try ^^
Now that i have Re-read, i think I'm not very clear in my question.
Just to clarify: when the params I need were located in the path for the API URL (like "register/user{userId})", it shows on the generated documentation.
When the params I need are requested via body (key:value), I had to put manually.
But I didn't try the new version yet.
As soon as I try, I'll give you the feedback ^^

**Comment by mpashkovskiy** [comment]
Closing the issue as no feedback is given. Feel free to reopen if issue is still exists.
