### ISSUE TITLE
how to use jwt token in swagger

### ISSUE THREAD

**Issue by Markomb87** [mpashkovskiy/express-oas-generator#18]
Hello i'm trying out your package its great but i don't find how to put jwt token into swagger or attach to request

**Comment by mpashkovskiy** [comment]
Hello, there is a possibility in the module to change swagger spec with custom method like this:
```javascript
generator.init(app, function(spec) {
  _.set(spec, 'info.title', 'New Title');
  _.set(spec, "paths['/path'].get.parameters[0].example", 2);
  return spec;
});
```

so accordingly to https://swagger.io/docs/specification/authentication/bearer-authentication/ I suppose you have to do something like following:

```javascript
generator.init(app, function(spec) {
  _.set(
    spec,
    'components.securitySchemes.bearerAuth',
    {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT'
    }
  );
  _.set(spec, "paths['/path'].get.security", [{bearerAuth:[]}]);
  return spec;
});
```

Some additional info could be found here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#jwt-bearer-sample

Please let me know if it works for you and sorry for late response.

**Comment by Markomb87** [comment]
tanks for response :+1: but  went with other solution but I will test this on other projects. looks great.

**Comment by mpashkovskiy** [comment]
Closing the issue, if you need anything feel free to reopen
