### ISSUE TITLE
SwaggerUI Execute doesn't work 

### ISSUE THREAD

**Issue by superandroid4848** [mpashkovskiy/express-oas-generator#19]
Hi,

I have embedded your code in my NodeJS App (server.js) 

When I open swagger-ui , I can see the routes , but when I try to execute the call it doesn't display the response .. (in browser network tab the call is successful and response is received) 

Also attaching swagger file which is generated (changed extensions while attaching)

Thanks,
Aniket.

[server.log](https://github.com/mpashkovskiy/express-oas-generator/files/2649168/server.log)

[swagger-spec.log](https://github.com/mpashkovskiy/express-oas-generator/files/2649145/swagger-spec.log)

**Comment by biki636** [comment]
I am also noticing the same exact issue where Swagger's execute functionality is not working.

**Comment by mpashkovskiy** [comment]
@superandroid4848, @biki636 have you run REST API tests or used service before opening Swagger UI? Could you try downgrade to version 0.1.25 and check if it works for you?

**Comment by mpashkovskiy** [comment]
Closing the issue as got no response. Feel free to reopen if the problem still exists.
