### ISSUE TITLE
multiple get routes are not considered with in the same parent route

### ISSUE THREAD

**Issue by venkataramkishore** [mpashkovskiy/express-oas-generator#2]
TypeScript code base: 
I have routes as follows
      this.router.get('/list', this.userCtrl.fetchAllUsers);
      this.router.get('/:id', this.userCtrl.fetchById);
      this.router.post('/create', this.userCtrl.createUser);
      this.router.put('/:id', this.userCtrl.updateById);
      this.router.delete('/:id', this.userCtrl.deleteById);
      this.router.patch('/:id', this.userCtrl.fetchById);

parent route is defined as follows 
this.app.use('/api/user', new UserRoute().getUserRoutes());

When i open the http://localhost:3000/api-docs 
1. swagger-ui does not show /:id GET route at all
2. PATCH request is never shown

**Comment by mpashkovskiy** [comment]
Hi Venkata will check it.

**Comment by mpashkovskiy** [comment]
Good catch! Bug is fixed.
Unfortunately I cannot publish latest version to https://www.npmjs.com/ but you can directly specify git repo as a dependancy and use version 0.1.15.
Like that:

```
"dependencies": {
    "express-oas-generator": "git://github.com/mpashkovskiy/express-oas-generator.git#0.1.15"
  },
```

Please let me know if it fixed the problem

**Comment by mpashkovskiy** [comment]
version 0.1.16 published to npm repo
