### ISSUE TITLE
Open Api 3 spec? 

### ISSUE THREAD

**Issue by ontehfritz** [mpashkovskiy/express-oas-generator#22]
Is there plans in the roadmap to add generation of the open api 3 spec?

**Comment by mpashkovskiy** [comment]
frankly speaking there was no plan, but I will read a bit about version 3 and let's see.

**Comment by sarpik** [comment]
fyi - I use [redoc](https://github.com/Redocly/redoc) to serve my documentation in production once `openAPI.json` is generated.

I just noticed their warning `[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0`!

I went into [their repo](https://github.com/Redocly/redoc) and found that they're using [swagger2openapi (npm)](https://www.npmjs.com/package/swagger2openapi)
(https://github.com/Mermade/oas-kit) to convert the openAPI from `v2` (aka swagger) to `v3`!

This means that it's totally possible to convert the v2 to v3!

/cc @mpashkovskiy

**Comment by mpashkovskiy** [comment]
Hm, that is really interesting. Do you have implementation in mind we can incorporate into express-oas-generator? How about creating PR?

**Comment by sarpik** [comment]
@mpashkovskiy I'm currently trying my best to create a production-ready implementation for my own app with express-oas-generator. The api being v2 does not bother me as it works, but I surely would like this solved. So after I get my thing working, I can surely take a look! I'll edit this if I start working on it.

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy 
Would you like me to take this one? `swagger2openapi` seems pretty straight forward to implement.

**Comment by maxiejbe** [comment]
@kiprasmel I've just seen your enhancement to start using OpenApi3 spec. Are you close to a PR? Can I help with that?

**Comment by kiprasmel** [comment]
@maxiejbe If you looked at a commit in my own project (https://github.com/kiprasmel/turbo-schedule/commit/5b9b49516df4a717ddd4a8469103810f8561c76e) - everything I changed was the types, since `redoc` (an alternative to swagger which renders the openAPI spec as html page - i.e. https://tvarkarastis.com/api/v1/docs) handles it automatically.

I haven't done anything for this project in regards to this issue - it's up for grabs!

**Comment by maxiejbe** [comment]
> @maxiejbe If you looked at a commit in my own project ([kiprasmel/turbo-schedule@5b9b495](https://github.com/kiprasmel/turbo-schedule/commit/5b9b49516df4a717ddd4a8469103810f8561c76e)) - everything I changed was the types, since `redoc` (an alternative to swagger which renders the openAPI spec as html page - i.e. https://tvarkarastis.com/api/v1/docs) handles it automatically.
> 
> I haven't done anything for this project in regards to this issue - it's up for grabs!
> 
> See also the comment above: [#22 (comment)](https://github.com/mpashkovskiy/express-oas-generator/issues/22#issuecomment-544294226)

Yes, the conversion with `swagger2openapi` seems pretty straight forward. Will take a look and let you know!

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy Should I overwrite the existing file or preserve both `v2` and `v3`?

**Comment by kiprasmel** [comment]
@mpashkovskiy Heh, perhaps make this behaviour configurable inside the initialization functions, something like this:

```ts
export type OpenApiSpecVersion = 2 | 3;
```

I'm just thinking about the correct default. Unless we're willing to do a major version bump, we should keep as-is, and encourage users to change it themselves. And when releasing a new major version - change the default.

**Comment by kiprasmel** [comment]
This got me thinking - perhaps we should track the things we'd like to change once doing a major version bump - like a mini roadmap issue?

Currently there's 2 upgrades I'm aware of:

1. I've proposed deprecating the `init` function and only providing the `handleRequests` and `handleResponses` utilities. This would allow us to focus on being more than just a *development only* thingie, and more closer to *production ready, auto-generation from tests/postman etc. based* solution (we're already close to it, but our documentation does not state nor reflect it).

2. The thing I just mentioned https://github.com/mpashkovskiy/express-oas-generator/issues/22#issuecomment-669331877

& probably more to come.

---

So yeah, perhaps we should track this:D

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel Please take a look at this draft PR #63 👍

**Comment by maxiejbe** [comment]
> @maxiejbe Heh, perhaps make this behaviour configurable inside the initialization functions, something like this:
> 
> ```ts
> export type OpenApiSpecVersion = 2 | 3;
> ```
> 
> I'm just thinking about the correct default. Unless we're willing to do a major version bump, we should keep as-is, and encourage users to change it themselves. And when releasing a new major version - change the default.

I'm still not considering this `version argument`. Will do on the next iteration, but wanted you to see how it looks like.

**Comment by mpashkovskiy** [comment]
How about serving both specs? So following urls will be available:

* `api-docs` - remains the same and serves Swagger UI with v2 spec
* `api-spec` - serves v2 spec
* `api-docs/v2` - alias to `api-docs`
* `api-spec/v2` - alias to `api-spec`
* `api-docs/v3` - serves Swagger UI with v3 spec
* `api-spec/v3` - serves v3 spec

Thus no extra config is needed.

As of major version change: well as long as we are careful and keep the changes backward compatible it is not needed. And so far we were doing great thanks to you @kiprasmel and @maxiejbe.

@kiprasmel could you elaborate a bit on`being more than just a development only thingie, and more closer to production ready`? What is needed to become `production ready`? The main concern about the usage of the module in production is sensetive data leakage and some computational overhead spec generation requires. Not sure if there is a good way to mitigate those risks.

**Comment by maxiejbe** [comment]
> * `api-docs` - remains the same and serves Swagger UI with v2 spec
> * `api-spec` - serves v2 spec
> * `api-docs/v2` - alias to `api-docs`
> * `api-spec/v2` - alias to `api-spec`
> * `api-docs/v3` - serves Swagger UI with v3 spec
> * `api-spec/v3` - serves v3 spec

Sounds good!

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel I would create an issue with the following roadmap:

- Big warning when `process.env.NODE_ENV === 'production'`. Even not applying the middleware.
- `init` waiting time is smart but hacky. I'm in favor of deprecating and shipping major version. If not, maybe implement #35 or find a more elegant way to do dynamic middleware inject (which is pretty risky).
- Smaller `README.md`, focused on "`advanced`" (unique) usage.
- OpenApi3 (in progress)

- `serveApiDocs` contains logic for `prepareApiDocs` that is not persisted until next request `handleResponses`. Shouldn't we save `api-spec.json` file before serving? Completely related to #50.
- Give the choice to avoid `api-spec.json` volatility. Now we're resetting every time, allow loading instead from existing `api-spec.json`.

**Comment by kiprasmel** [comment]
> How about serving both specs? So following urls will be available:
> 
> * `api-docs` - remains the same and serves Swagger UI with v2 spec
> * `api-spec` - serves v2 spec
> * `api-docs/v2` - alias to `api-docs`
> * `api-spec/v2` - alias to `api-spec`
> * `api-docs/v3` - serves Swagger UI with v3 spec
> * `api-spec/v3` - serves v3 spec
> 

I don't think that one can intuitively differenciate between `api-docs` and `api-spec`, thus creating confusion. Additionaly, there'd be too many ways to do the same thing:D

I suggest keeping the same `api-docs` + either `/v2` or `v3` - it would stay backwards compatible and intuitive.

**Comment by maxiejbe** [comment]
We're currently serving both `api-docs` and `api-spec`. The change in this case would be to split the routes by version, with one of them as default. Take a look at the PR changes 👍

**Comment by kiprasmel** [comment]
> @mpashkovskiy @kiprasmel I would create an issue with the following roadmap:
> 
> * Big warning when `process.env.NODE_ENV === 'production'`. Even not applying the middleware.
> * `init` waiting time is smart but hacky. I'm in favor of deprecating and shipping major version. If not, maybe implement #35 or find a more elegant way to do dynamic middleware inject (which is pretty risky).
> * Smaller `README.md`, focused on "`advanced`" (unique) usage.
> * OpenApi3 (in progress)
> * Give the choice to avoid `api-spec.json` volatility. Now we're resetting every time, allow loading instead from existing `api-spec.json` #52

Like, exactly what I was thinking:D Leggo 🚀

**Comment by kiprasmel** [comment]
@mpashkovskiy 

> As of major version change: well as long as we are careful and keep the changes backward compatible it is not needed. And so far we were doing great thanks to you @kiprasmel and @maxiejbe.

ayyy cheers, I think we both found value in the project ourselves, thus decided to contribute further:D

> @kiprasmel could you elaborate a bit on `being more than just a development only thingie, and more closer to production ready`? What is needed to become `production ready`? The main concern about the usage of the module in production is sensetive data leakage and some computational overhead spec generation requires. Not sure if there is a good way to mitigate those risks.

I mean that the documentation (primarily, the README, & perhaps examples) warn against using this in production and give higher priority to the basic `init` usage instead of the advanced `handle(Requests|Responses)` -- because we can have this in production - I've had it for a while now - not to actively listen, but to be used together with tests at project's build time to generate static documentation - that's what I've been doing anyways and I think we can push this narrative quite far.

**Comment by mpashkovskiy** [comment]
> > @mpashkovskiy @kiprasmel I would create an issue with the following roadmap:
> > 
> > * Big warning when `process.env.NODE_ENV === 'production'`. Even not applying the middleware.
> > * `init` waiting time is smart but hacky. I'm in favor of deprecating and shipping major version. If not, maybe implement #35 or find a more elegant way to do dynamic middleware inject (which is pretty risky).
> > * Smaller `README.md`, focused on "`advanced`" (unique) usage.
> > * OpenApi3 (in progress)
> > * Give the choice to avoid `api-spec.json` volatility. Now we're resetting every time, allow loading instead from existing `api-spec.json` #52
> 
> Like, exactly what I was thinking:D Leggo 🚀

Sounds good to me

**Comment by mpashkovskiy** [comment]
aaand, done
