### ISSUE TITLE
swagger ui api response not able to update at a time 

### ISSUE THREAD

**Issue by chandusr** [mpashkovskiy/express-oas-generator#27]
Hi,
 
i am working with swagger for node api documentation with express-oas-generator

my main problem as every thing working for me until api call 
i made api call its giving response it also updated in swagger.json file but at a run time the response is not shown in swagger ui 
after clicking execute button i got response but not update in swagger ui

 "express-oas-generator": "^1.0.7",
  "swagger-ui-express": "^4.0.6",

![Capture](https://user-images.githubusercontent.com/24756336/61347244-bdc7ae00-a879-11e9-9866-bf4ad9894508.PNG)
 
![Capture](https://user-images.githubusercontent.com/24756336/61347119-4b56ce00-a879-11e9-8daa-8e336caafe90.PNG)

**Comment by mpashkovskiy** [comment]
Hi chandusr, checking

**Comment by mpashkovskiy** [comment]
I noticed on your screenshot that there are some errors in Developer Tools Console. Could you share what is there?
Also there are two calls in network console to authenticate endpoint and first is red. Could you show why is it red?

**Comment by chandusr** [comment]
ya sure that issues from my side only that's vpn problem like net work issues and i also found partial solution for that before writing json in swagger.json  i set the empty  responses object for each api
is that wright solution. 
![Capture4](https://user-images.githubusercontent.com/24756336/61946913-69cb7080-afc1-11e9-99fd-6a58be1a86b9.PNG)
![Capture5](https://user-images.githubusercontent.com/24756336/61946914-6b953400-afc1-11e9-9a04-4bfeb7c5049f.PNG)

**Comment by mpashkovskiy** [comment]
"i set the empty responses object for each api" - how do you do that?

**Comment by chandusr** [comment]
const expressOasGenerator = require('express-oas-generator');
expressOasGenerator.init(app, function(spec) {
    for(var index in spec.paths) { 
   _.set(spec, 'paths['+index+'].post.responses',{});
}
}


like this

**Comment by mpashkovskiy** [comment]
That is an excellent catch! Fixed it. Could you try version 1.0.9? Manual initialization of responses not needed anymore.

**Comment by chandusr** [comment]
thanks @mpashkovskiy
