### ISSUE TITLE
Enable custom param for renaming api-docs path

### ISSUE THREAD

**Issue by pragmaticivan** [mpashkovskiy/express-oas-generator#28]
currently it's manually put as `/api-docs`, would be nice to be able to provide a param to rename it to `/docs` for example

**Comment by MateRyze** [comment]
Can I help with this issue?

**Comment by mpashkovskiy** [comment]
@MateRyze it would be nice! Create a PR please.

**Comment by mpashkovskiy** [comment]
Thanks to @MateRyze now it is available. Update to v1.0.11.
You can pass fith parameter to generator.init(). See https://github.com/mpashkovskiy/express-oas-generator/pull/30/files#diff-0cbce0737e7633bd0d2550fc50ea5cb8R237 for more info.
