### ISSUE TITLE
Body params not being picked up

### ISSUE THREAD

**Issue by Nathan961207** [mpashkovskiy/express-oas-generator#29]
prices.js 
  ```javascript
const express = require("express");
const router = express.Router();
const { soap } = require("strong-soap");
const urlv6 = "./wsdl/series_data_v6.WSDL";
const clientPromise = new Promise((resolve, reject) =>
  soap.createClient(urlv6, {}, (err, client) =>
    err ? reject(err) : resolve(client)
  )
);

router.post("/", function(req, res, next) {
  clientPromise
    .then(client => ({ client, request: req.body }))
    .then(invokeOperations)
    .then(results =>{
      res.json(results);
      next();
    })
    .catch(({ message: error }) => {
      res.json(error);
      next(error);
    });
});

const invokeOperations = ({ client, request }) =>
  new Promise((resolve, reject) => {
    client.setSecurity(
      new soap.BasicAuthSecurity(process.env.SEB_USER, process.env.SEB_PASSWORD)
    );
    client.RequestSeriesData(request, (err, result) => {
      err ? reject(err) : resolve(result);
    });
  });

module.exports = router;

  ```

I get the following error `Error: Can't set headers after they are sent.`
I read the other issues and i noticed if I don´t call `next()` then no parameters will be picked up but when i use `next()` it complains about my header being set.

**Comment by mpashkovskiy** [comment]
checking

**Comment by mpashkovskiy** [comment]
Hm, frankly speakng cannot reproduce the problem

This is what I'm doing:

```javascript
const express = require('express');
const bodyParser = require('body-parser');
const generator = require('./index.js');

const app = express();
generator.init(app, function (spec) { return spec; }, './test_spec.json');
app.use(bodyParser.json({}));

let router = express.Router();
router.post("/", function(req, res, next) {
  invokeOperations(req.body)
    .then(results => {
      res.json(results);
      next();
    })
    .catch(({ message: error }) => {
      res.json(error);
      next(error);
    });
});

const invokeOperations = request =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(request), 5000);
  });

app.use(router);
app.set('port', 8080);
app.listen(app.get('port'));
```

and then calling `curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:8080` forces app to generate specification with body params.

Any ideas how can I reproduce the problem are apprecated.

**Comment by mpashkovskiy** [comment]
@Nathan961207 is it still a problem?

**Comment by mpashkovskiy** [comment]
BTW do you use the latest version?

**Comment by Nathan961207** [comment]
Yes, I use the latest version. I will try to copy your setup and see if that works.

**Comment by obai-d** [comment]
Same issue here as well. I have my route like this:

```
router.post('/', async (req, res /* , next */) => {
  const {
    recipe_name: recipeName,
  } = req.body;
  ...
  ...
});
```

I can call the api with `recipe_name` and see the expected result. But the generated `swagger.json` has no info about the body param.

**Comment by mpashkovskiy** [comment]
@obai-d it is important to call `next()` at the very end of your handler, here is some more explanation about it: https://github.com/mpashkovskiy/express-oas-generator/issues/24#issuecomment-518607492

**Comment by mpashkovskiy** [comment]
@Nathan961207 I think I found a problem! There is no `next()` call in your error handler:

```javascript
// error handler
app.use(function(err, req, res, next) {
 // set locals, only providing error in development
 res.locals.message = err.message;
 res.locals.error = req.app.get("env") === "development" ? err : {};

 // render the error page
 res.status(err.status || 500);
 res.render("error");
});
```

Try

```javascript
// error handler
app.use(function(err, req, res, next) {
 // set locals, only providing error in development
 res.locals.message = err.message;
 res.locals.error = req.app.get("env") === "development" ? err : {};

 // render the error page
 res.status(err.status || 500);
 res.render("error");
next();
});
```

Let me know if it works.

**Comment by Nathan961207** [comment]
@mpashkovskiy That did not work, nice catch tho.
Could you possibly implement some function to send the body params without calling `next()`?

```js

    console.log(res.headersSent ) // false
    res.json(results);
    console.log(res.headersSent ) // true
    // Performing next after the header is sent will always be an error
    next();
````

**Comment by obai-d** [comment]
@mpashkovskiy calling next() does the job for me. Thanks!

**Comment by mpashkovskiy** [comment]
@Nathan961207 unfortunately `next()` is neccesary here because this is how expressjs works.

Can you check one thing. In your examples with header when you are calling `next()` error middleware starting to change response and that is why you get an error and only after express-oas-generator middleware starts to work (if does nothing to request/response objects). What if you change it so it modifies the response only if there is an actual error. Something like that:

```javascript
app.use(function(err, req, res, next) {
  if (err) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get("env") === "development" ? err : {};

    // render the error page
    res.status(err.status || 500);
    res.render("error");
  }
  next();
});
```

**Comment by mpashkovskiy** [comment]
Could you also try to disable error middleware and call `next()` in your router to see if it helps?

**Comment by Nathan961207** [comment]
Removing this middleware solved the issue....Thanks for your help!
`app.use("/", swaggerUi.serve, swaggerUi.setup(swaggerDocument));`
