### ISSUE TITLE
Use object for optional arguments

### ISSUE THREAD

**Issue by MateRyze** [mpashkovskiy/express-oas-generator#35]
Current init function header:
https://github.com/mpashkovskiy/express-oas-generator/blob/c6c6ec8a10fc88e460cd3695d679f1e83ad13d86/index.js#L145

I think that it would make the call of the `init` function easier when the optional arguments are passed as an object with default params like:
```javascript 
module.exports.init = (aApp, aPredefinedSpec, { aPath, aWriteInterval, aApiDocsPath } = { aPath: '', aWriteInterval: 10 * 1000, aApiDocsPath: 'api-docs'}) => {...}
```

**Comment by sarpik** [comment]
I strongly agree. The init function gets (*is*) messy and if we add more options in the future, it will get cluttered even more.

While we're at it, I think that the second parameter `aPredefinedSpec` should also be optional, since you're allowed to pass in an empty object to it, so why not make it optional too?

**Comment by mpashkovskiy** [comment]
That is a good idea. But it will break existing integration. I will create v2.0.0 of the module and PR is warmly welcomed!

**Comment by sarpik** [comment]
I'll create a PR here after we finish with #32.

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel Would you agree to close this one in favor of #65 ?

**Comment by kiprasmel** [comment]
@maxiejbe 

> Would you agree to close this one in favor of #65 ?

Absolutely.

**Comment by mpashkovskiy** [comment]
> @mpashkovskiy @kiprasmel Would you agree to close this one in favor of #65 ?

Sorry, not sure that understand how switching to single object parameter in `init/handleResponses` related to deprectaion of `init`. Could you please clarify?

**Comment by maxiejbe** [comment]
> > @mpashkovskiy @kiprasmel Would you agree to close this one in favor of #65 ?
> 
> Sorry, not sure that understand how switching to single object parameter in `init/handleResponses` related to deprectaion of `init`. Could you please clarify?

`handleResponses` already has a single object parameter. This is specific for init and we're gonna deprecate it 😄
