### ISSUE TITLE
Is there a way to ignore certain routes or apply any sort of filter?

### ISSUE THREAD

**Issue by obai-d** [mpashkovskiy/express-oas-generator#37]
I love the option for outputting specification to a `.json` file. However the problem I face is, the file grows so large. Based on my usage pattern, some of the routes get tons of examples added. And some others don't have any yet. 

It will be great if we can tightly control what goes into the specification json. Things like, store only 1-2 examples per api.

I believe the second argument to `init()` is for this purpose. But I am not sure how exactly to tweak it for the above need. 

I will be happy to create a documentation PR if anybody can shed some light here.

**Comment by mpashkovskiy** [comment]
Second argument is used to modify specification, indeed, but I think it is not used when we write specificatoion into the file. I thought only one example is generated per endpoint. I will check.

**Comment by sarpik** [comment]
From express's `4.x` docs:

I'd recommend reading the whole thing - https://expressjs.com/en/4x/api.html#router.use

> The order in which you define middleware with router.use() is very important. They are invoked sequentially, thus the order defines middleware precedence. For example, usually a logger is the very first middleware you would use, so that every request gets logged.

```js
var logger = require('morgan')
var path = require('path')

router.use(logger())
router.use(express.static(path.join(__dirname, 'public')))
router.use(function (req, res) {
  res.send('Hello')
})
```

> Now suppose you wanted to ignore logging requests for static files, but to continue logging routes and middleware defined after logger(). You would simply move the call to express.static() to the top, before adding the logger middleware:

```js
router.use(express.static(path.join(__dirname, 'public')))
router.use(logger())
router.use(function (req, res) {
  res.send('Hello')
})
```

...

> NOTE: Although these middleware functions are added via a particular router, when they run is defined by the path they are attached to (not the router). Therefore, middleware added via one router may run for other routers if its routes match. For example, this code shows two different routers mounted on the same path:

I see potential, but I haven't yet tried anything like this.
Once again, see https://expressjs.com/en/4x/api.html#router.use

**Comment by obai-d** [comment]
> I thought only one example is generated per endpoint. I will check.

@mpashkovskiy did you get a chance to check that? It is generating multiple examples for me. Not sure if I missed something.

**Comment by sarpik** [comment]
@obai-d Just an FYI - I had the same issue previously & thus used this monstrosity to trim the length of my examples' arrays to `1`.

```ts
/**
 * trimExampleLengthToOne.ts
 *
 * Ported from https://github.com/sarpik/turbo-schedule
 *
 * Copyright (c) 2019 Kipras Melnikovas
 * Use freely
 */

import { OpenAPIV3 } from "openapi-types";

/** debugging purposes */
function logEmpty(what: string) {
	console.log(`\`${what}\` not found / empty`);
}

export function trimExampleLengthToOne<T extends OpenAPIV3.Document>(generatedDocsReference: T): T {
	const generatedDocs: T = { ...generatedDocsReference };

	Object.entries(generatedDocs.paths).forEach(([_pathKey, pathValue]) => {
		Object.entries(pathValue as object).forEach(([_reqMethodKey, reqMethodValue]) => {
			if (!reqMethodValue?.responses) {
				logEmpty("responses");
			} else {
				Object.entries(reqMethodValue.responses as object).forEach(([_resCodeKey, resCodeValue]) => {
					console.log("resCodeValue", resCodeValue);
					if (!resCodeValue?.schema?.properties) {
						logEmpty("schema / schema.properties");
					} else {
						Object.entries(resCodeValue.schema.properties as object).forEach(([_propKey, propValue]) => {
							if (!propValue?.example) {
								logEmpty("property / property.example");
							} else {
								if (!Array.isArray(propValue.example)) {
									// continue;
								} else {
									if (propValue.example.length > 1) {
										propValue.example = propValue.example[0];
										console.log("  -> Sliced example's array to contain only 1 element!");
										console.log("Example", propValue.example);
									}
								}
							}
						});
					}
				});
			}
		});
	});

	return generatedDocs;
}
```

It's written in TypeScript, but you can easily convert it to JavaScript.

I no longer need this since I run tests with a fake database & all data is whatever I provide in the tests, so it's fitting perfectly.

We might consider something like this in the future with maybe an option like `limitExampleArrayLengthTo` or something:D Feedback welcome!

**Comment by obai-d** [comment]
Thanks @sarpik !

**Comment by mpashkovskiy** [comment]
fixing it, hold on

**Comment by mpashkovskiy** [comment]
@obai-d , @sarpik  could you please try version 1.0.18

**Comment by obai-d** [comment]
@mpashkovskiy just verified it, works 👍  Thanks a bunch!

**Comment by sarpik** [comment]
@mpashkovskiy seems to be working fine:)
Should we mention this in the docs? Someone might want the opposite behaviour and might get confused. Thus, maybe we should make this optional? (After #35)

**Comment by mpashkovskiy** [comment]
frankly speaking I doubt that anyone would like to have opposite behaviour, it was more of a bug than a feature :)

**Comment by sarpik** [comment]
Fair enough, let's do something else that's useful then:D

**Comment by sarpik** [comment]
Hey there, could we re-open this?
I'd like to make the behaviour, introduced in d8f19dc2a1891400389dc01e8de6f0e9246a5d59, optional.
