### ISSUE TITLE
No api endpoints are generated

### ISSUE THREAD

**Issue by anodynos** [mpashkovskiy/express-oas-generator#4]
First of all thank for this library, it will be amazing if it works for us (tried 0.1.16 & 0.1.18).

So we get no endpoint generated, initially we thought because of   [`if (req.url.startsWith('/api-')) {`](https://github.com/mpashkovskiy/express-oas-generator/blob/d633de6/index.js#L108) (and ours does start with `/api-`) so we comment it out. Still no results.

Next, we noticed that the line [`const pathKeys = Object.keys(spec.paths);`](https://github.com/mpashkovskiy/express-oas-generator/blob/d633de6/index.js#L97) always produces an empty array initially, so the `getPathKey` function always returns undefined and no endpoints get documented. 

Could you please help us with this?

**Comment by mpashkovskiy** [comment]
Hi Angelos, I'm glad to help. Could you please post example of endpoint initialisation code so I can reproduce it.

**Comment by anodynos** [comment]
Thanks so much Matvey. So after stripping our app apart without being able to fix it, we ended up with a hello world express app which is still not working: 

```
const express = require(‘express’); // “version”: “4.13.4"
const expressOasGenerator = require(‘express-oas-generator’); // 0.1.18
const bodyParser = require(‘body-parser’); // “version”: “1.13.3"

const app = express();
expressOasGenerator.init(app, {});

app.use(bodyParser.json());

app.post( `/hello`, (req, res) => {
 console.log(req.body);
 res.setHeader(‘Content-Type’, ‘text/plain’)
 return res.end(‘whatever’);
});

app.listen(5000);
``` 

We invoke `POST /hello` and then we hit `GET /api-spec` and we get 
```
{
   “info”: {
       “title”: “hello”,
       “version”: “0.0.0”,
       “description”: “[Specification JSON](/api-spec)”
   },
   “paths”: {},
   “swagger”: “2.0"
}
```

**Comment by mpashkovskiy** [comment]
Hi Angelos, I fixed the problem and updated tests. Could you please check version 0.1.19 and let me know if it works for you.

**Comment by anodynos** [comment]
Matvey, that was great, thanks so much, it started working! 

The only problem now is that although it is pre-populating the endpoints and documents the endpoint `responses` properly as we hit them, it is _not_ populating the parameters at all, they remain an empty array.

**Comment by mpashkovskiy** [comment]
It is strange, I thought I covered those cases quite good in [spec/index_tests.js](https://github.com/mpashkovskiy/express-oas-generator/blob/master/test/index_tests.js)
Could you give me endpoint path and request/response from it so I can extend tests and reproduce your case?

**Comment by anodynos** [comment]
Thanks for your response Matvey.

So far we've identified 2 problems - I am note sure if this is the expected behavior: 

1) Responses of `text/plain` are not picked up
```
app.post(‘/hello/:id’, (req, res) => {
 res.setHeader(‘Content-Type’, ‘text/plain’);
 res.send(‘world’);
})
``` 
gives 
```
     “/hello/{id}“: {
           “post”: {
               “consumes”: [
                   “application/json”
               ],
               “parameters”: [
                   {
                       “name”: “id”,
                       “in”: “path”,
                       “required”: true
                   }
               ],
               “produces”: [
                   “text/plain”
               ],
               “responses”: {
                   “200”: {}
               }
           }
       }
```
but the rsponse is not populated with example (after we've used it). 
The param in the url is correctly documented. 

2) Request body is not documented - with this endpoint 
```
app.post(‘/hello2’, (req, res) => {
 res.setHeader(‘Content-Type’, ‘application/json’);
 res.send({key: ‘secret’});
})
```

we get 
``` “/hello2": {
           “post”: {
               “consumes”: [
                   “application/json”
               ],
               “parameters”: [],
               “produces”: [
                   “application/json”
               ],
               “responses”: {
                   “200": {
                       “schema”: {
                           “type”: “object”,
                           “properties”: {
                               “key”: {
                                   “type”: “string”,
                                   “example”: “secret”
                                }...
```
after we've send an `{"foo": "bar"}` object to it. I guess it should produce an example out of it, right?

I really appreciate your help & please let me know if I can help further.

**Comment by mpashkovskiy** [comment]
Hi Angelos. I added handling of `text/plain` responses and added [test for POST](https://github.com/mpashkovskiy/express-oas-generator/blob/master/test/index_tests.js#L81) parameters handling. In your case POST handling doesn't work because in handling function call of `next()` middleware is missing. So it should be:

```
app.post(‘/hello2’, (req, res, next) => {
  res.setHeader(‘Content-Type’, ‘application/json’);
  res.send({key: ‘secret’});
  next(); // <--- we have to call any other middleware in chain, in our case it will be 'spying' middleware
})
```

Also please make sure you configured [body parser middleware](https://github.com/mpashkovskiy/express-oas-generator/blob/master/test/index_tests.js#L34) in your app and send [right header](https://github.com/mpashkovskiy/express-oas-generator/blob/master/test/index_tests.js#L87)

**Comment by mpashkovskiy** [comment]
please try version 0.1.20 and let me know if it works for you

**Comment by anodynos** [comment]
Thank you Matvey - it worked like a charm! 

A possible _exotic_ improvement would be to augment the body parameters example, as new keys are observed, but that not part of this issue! 

Your work is highly appreciated, thank you very much!
