### ISSUE TITLE
post payload documentation

### ISSUE THREAD

**Issue by rvleyden** [mpashkovskiy/express-oas-generator#41]
Hello,

It is a great tool, but when documenting a Post it is not displaying the payload in the swager doc. How can I do that?

**Comment by sarpik** [comment]
Could you elaborate?

Do you mean a POST request, like `router.post()`?

Could I see the relevant code?

I've set up express-oas-generator [in my own app](https://github.com/sarpik/turbo-schedule/tree/master/server) and it works fine, maybe I could help you with something?

**Comment by mpashkovskiy** [comment]
@rvleyden please make sure you call next() in your router and middleware. Here is a relevant comment https://github.com/mpashkovskiy/express-oas-generator/issues/24#issuecomment-518607492

**Comment by mpashkovskiy** [comment]
@rvleyden hopefully our comments helped to fix the problem, so closing the issue.
Please feel free to reopen if problem still exists.
