### ISSUE TITLE
The new `handleResponses` and `handleRequests` method does work

### ISSUE THREAD

**Issue by sarpik** [mpashkovskiy/express-oas-generator#42]
I was trying to implement the new functionality, provided by #39.

It wouldn't work. 

~~I found out what was wrong, here's a quick patch (solves the issue, but unfinished yet):~~ I thought this solved the issue, but it did not. I'm a little lost now.

```diff
diff --git a/node_modules/express-oas-generator/index.js b/node_modules/express-oas-generator/index.js
index 753ce13..4d5a3ec 100644
--- a/node_modules/express-oas-generator/index.js
+++ b/node_modules/express-oas-generator/index.js
@@ -276,7 +276,7 @@ function handleResponses(expressApp, options = { pathToOutputFile: undefined, wr
  *
  * @returns void
  */
-function handleRequests(options = { path: 'api-docs', predefinedSpec: {} }) {
+function handleRequests(expressApp, options = { path: 'api-docs', predefinedSpec: {} }) {
   /** make sure the middleware placement order (by the user) is correct */
   if (responseMiddlewareHasBeenApplied !== true) {
     throw new Error(WRONG_MIDDLEWARE_ORDER_ERROR);
@@ -286,7 +286,7 @@ function handleRequests(options = { path: 'api-docs', predefinedSpec: {} }) {
   responseMiddlewareHasBeenApplied = false;
 
   /** middleware to handle REQUESTS */
-  app.use((req, res, next) => {
+  expressApp.use((req, res, next) => {
     try {
       const methodAndPathKey = getMethod(req);
       if (methodAndPathKey && methodAndPathKey.method && methodAndPathKey.pathKey) {
```

What was the problem is that I thought that the global `app` variable would hold a reference to the `app` [we pass in from the first handler - `handleResponses`](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L240-L248).

Thus [I was not asking for the `app` variable in the second handler - `handleRequests`](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L306) and just [used the global one](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L316).

That did not work.
As seen in the patch above - after receiving the `expressApp` variable inside the `handleRequests` function -- ~~everything worked fine.~~

---

My question is -- do we *need* the global `app` variable?

if yes, then how would we go about it at the `handleRequests` handler - override the global `app` variable with the passed in `expressApp` variable?

(That would probably make sense because it's the latest one), but do we need the global variable anyway then? (I haven't looked if it's needed for anything else yet - sorry:D)

---

I currently cannot get the new setup to work, so that needs something done too.

---

also, we currently [are NOT passing in the `app` variable into `handleRequests` from the `init` function](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L397) - and it still works fine.
I don't know what's up.

Also, currently [the docs state that you need to pass in the `app` variable into the `handleRequests` handler](https://github.com/mpashkovskiy/express-oas-generator/blob/master/README.md#L85) - that's not true, because it accepts only an `options` object. We'll update that later too.

**Comment by mpashkovskiy** [comment]
fixed the problem, see https://github.com/mpashkovskiy/express-oas-generator/commit/fae64b26fda2b40d66a99cd4594d3a21b1778909 , and published new v1.0.15

I'm going to refactor code a bit to make `handleRequests()` recieve no args.

**Comment by mpashkovskiy** [comment]
let me know if there is still other problems

**Comment by mpashkovskiy** [comment]
Refactoring done: https://github.com/mpashkovskiy/express-oas-generator/commit/1a2a5c3362474b17b4be917df8549cf4bfcafd39 and new v1.0.16 is published

May I ask you to check JS doc comments and align those with code?

**Comment by sarpik** [comment]
I'll try it out and inform you tomorrow, thanks!

**Comment by sarpik** [comment]
Alright, this [works](https://github.com/sarpik/turbo-schedule/blob/master/server/src/server.ts#L30-L33) [great](https://github.com/sarpik/turbo-schedule/blob/master/server/src/server.ts#L83-L89)!

I'll check the jsdoc comments soon.
Providing type definitions for typescript might also be useful, like @DefinitelyTyped. I've never done that, but I'll see what I can do:D
