### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sarpik** [mpashkovskiy/express-oas-generator#44]
I noticed this project doesn't have a license yet.

I've been using https://choosealicense.com/ for a while now and it's great for choosing an OSS license.

For the best availability, I think that the [MIT License](https://choosealicense.com/licenses/mit/) would be the most appropriate, just like [express itself](https://github.com/expressjs/express/blob/master/LICENSE).

Though you can explore the licenses here: https://choosealicense.com/licenses/, or if you want in depth - here: https://choosealicense.com/appendix/. I'd still recommend MIT though:)

I can create a PR.

Edit:

It seems like [you've put the ISC license inside `package.json`](https://github.com/mpashkovskiy/express-oas-generator/blob/master/package.json#L29) - that's great, but I think that you need to place the license's file inside the repository too.

**Comment by mpashkovskiy** [comment]
Licence is defined in `package.json`. At the moment it is ISC.
I will check MIT license.
