### ISSUE TITLE
request bodies are not captured

### ISSUE THREAD

**Issue by nk2580** [mpashkovskiy/express-oas-generator#45]
when implementing this tool i have noticed that request bodies are not captured.
can someone shed some light as to why this might be the case ?

**Comment by mpashkovskiy** [comment]
Could you try this: https://github.com/mpashkovskiy/express-oas-generator/issues/24#issuecomment-518607492 ?

**Comment by nk2580** [comment]
As it turns out this was a secondary issue. Once I added the call to `next()` and did the advanced setup it all worked.. I think there’s some issue with my custom middleware breaking the request inspection.
