### ISSUE TITLE
Support for mongoose model definitions

### ISSUE THREAD

**Issue by maxiejbe** [mpashkovskiy/express-oas-generator#46]
In order to have **mongoose model definitions**, it could be pretty useful to integrate a library such as:

- https://github.com/giddyinc/mongoose-to-swagger
- https://github.com/simonguest/swagger-mongoose

Matching route requests/responses with model definitions must be hard to implement. 
Just a **read-only** implementation would be great!

An interface like this could work:
```
expressOasGenerator.handleResponses(server, {
    specMongooseModelsPath: './models',
    specMongooseIncludeModels: ['User', 'Blog', ...],    
});
```
Thanks in advance!

**Comment by sarpik** [comment]
Hey there, thanks for the request(s)!

I'm afraid that I and the owner don't have much time available right now to implement this:/ If you (or anyone else) would like to try to implement this & create a PR - we'd gladly accept!

**Comment by maxiejbe** [comment]
@sarpik Thanks for your reply. Sure, will give it a try! 😄

**Comment by JeffJassky** [comment]
@maxiejbe Any chance you decided to take that on? I was looking for the same thing :)

**Comment by maxiejbe** [comment]
> @maxiejbe Any chance you decided to take that on? I was looking for the same thing :)

Not yet, but planning to start soon!

**Comment by maxiejbe** [comment]
Hi everyone!
Here's the PR: https://github.com/mpashkovskiy/express-oas-generator/pull/61.
This is my first time contributing to this repository, wanna take a look @kiprasmel @mpashkovskiy ?
Thanks!

**Comment by mpashkovskiy** [comment]
Hey @maxiejbe thanks for PR! I reviewed it.

**Comment by maxiejbe** [comment]
> Hey @maxiejbe thanks for PR! I reviewed it.

Fixed them all 😄

**Comment by mpashkovskiy** [comment]
PR is merged, new version is on the way
