### ISSUE TITLE
Support for grouping operations by tag

### ISSUE THREAD

**Issue by maxiejbe** [mpashkovskiy/express-oas-generator#47]
It would be awesome to **group operations by tags**:

https://swagger.io/docs/specification/grouping-operations-with-tags/

By setting a flag:
```
expressOasGenerator.handleResponses(server, {
    specGroupByTag: true
});

```

You could group by the first route path after base url (aka controller name). REST example:
- GET /api/`users`
- GET /api/`users`/:id
- POST /api/`users`

All those endpoints could be tagged as **users**.

Thanks in advance!

**Comment by mpashkovskiy** [comment]
One of the problems here is that paths could be really different. For example:

* users/:id
* api/users/:id
* api/v1/users/:id
* get_user_by_id/:id (C# old school schema I think)

and many more, so I'm a bit hesitent to add this functionality.

@sarpik what is your opinion here?

**Comment by sarpik** [comment]
yeah no clue about tags - haven't used them yet, sorry.

**Comment by maxiejbe** [comment]
@kiprasmel tags are really useful to group operation (commonly by resources).
Once we have the definitions (See issue #46) I can easily include tag if path contains resource name (or its plural).

**Comment by mpashkovskiy** [comment]
@maxiejbe indeed it is a usefull feature, do you have in mind any algorithm how to extract tags from paths?

**Comment by maxiejbe** [comment]
> @maxiejbe indeed it is a usefull feature, do you have in mind any algorithm how to extract tags from paths?

I would implement it backwards. Array of tags supplied as an argument (init, handleResponses). Tag the paths if they contain any of those. Simple to implement, would give more flexibility!

**Comment by mpashkovskiy** [comment]
sounds like a good approach, would you create a PR?

**Comment by maxiejbe** [comment]
> sounds like a good approach, would you create a PR?

Sure, will let you know!

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel Created PR #62. Let me know!

**Comment by mpashkovskiy** [comment]
I think we can close that one as we have the PR
