### ISSUE TITLE
docs return in json format

### ISSUE THREAD

**Issue by pepepaco** [mpashkovskiy/express-oas-generator#48]
the header must be set to html in the serveApiDocs method like this:
```
  app.use(packageInfo.baseUrlPath + '/' + swaggerUiServePath, swaggerUi.serve, (req, res) => {
    res.setHeader('Content-Type', 'text/html');
    swaggerUi.setup(patchSpec(predefinedSpec))(req, res);
  });
```

**Comment by mpashkovskiy** [comment]
I'll take a look

**Comment by mpashkovskiy** [comment]
fixed, and looks like all tests passed, @pepepaco @sarpik could you please confirm that it works for you?

**Comment by pepepaco** [comment]
it works, i have on issue with the css but i believe its due to the nodejs app configuration.
thank you!.
