### ISSUE TITLE
Documentation not being updated when testing api with Jest

### ISSUE THREAD

**Issue by pedrokohler** [mpashkovskiy/express-oas-generator#49]
I'm not sure how to create the example calls for my API.

While doing it manually with postman worked and it added the examples, I couldn't manage to make it work with a jest test suite using supertest.

Is there a way to do with a test suite instead of having to make the request manually?

If so, can you provide an example?

**Comment by sarpik** [comment]
Hey @pedrokohler - I think I can help you here:)

I've got my project's test setup just like that - Jest + supertest.
Here it is: https://github.com/sarpik/turbo-schedule
(particullary, https://github.com/sarpik/turbo-schedule/blob/master/server/src/test)

I'll explain the setup here:

1. In the `test/setup.ts` file, I start up the server, as seen here:

https://github.com/sarpik/turbo-schedule/blob/162343ead7e64939bd0266418f453302f0a35924/server/src/test/setup.ts#L30

which just [calls `app.listen()`](https://github.com/sarpik/turbo-schedule/blob/162343ead7e64939bd0266418f453302f0a35924/server/src/server.ts#L105)

2. In my `test/utils.ts` file, I create a `request` wrapper for `supertest` to always use the same URL for making requests

https://github.com/sarpik/turbo-schedule/blob/1b3b8d6e9ff5e242831f1002efb4a84e5fccd0df/server/src/test/utils.ts#L28

(the whole file explains things pretty well)

3. In my test suites, I use the `request` wrapper from `test/utils.ts` file to make requests.

https://github.com/sarpik/turbo-schedule/blob/1b3b8d6e9ff5e242831f1002efb4a84e5fccd0df/server/src/test/student.test.ts#L11-L27

and that's it! Anything else I could help with?

Hopefully this was useful:) We definitely should create an example for this - will take a look soon!

---

Some notes:

I've previously tried starting up a separate server for each test case or suite, and both times it sucked - most notably, the speed was slow, and then other concurrency issues arose - I now don't remember exactly what happened, but I spent a lot of time debugging "why Jest doesn't work" the way "it should", but it was actually me myself messing something up, and once - not using promises properly. Feel free to ask if you encounter any issues with this and testing - I might be able to help further.

Sidenote: You might also find this useful (which we should probably implement here as an option:D): https://github.com/sarpik/turbo-schedule/blob/83253ae70314790d76f7f2cfeb5ef9811503ae64/server/src/server.ts#L36-L57

**Comment by pedrokohler** [comment]
Hello @sarpik Thank you very much for your detailed explanation.

I tried to run an experiment based on it and though I didn't fully understand what you did there despite of your awesome explanation, I was able to run it, however it didn't generate the documentation as I expected.

Maybe I'm doing something wrong or it just isn't suppose to do what I really wanted.

I expected that it would have generated a swagger.json file automatically after the tests run.

I used two files to (kinda) try to reproduce what you did:

index.js

```
const express = require('express');	
const fs = require('fs');
const { handleResponses, handleRequests } = require("express-oas-generator");

const openAPIFilePath = 'openAPI.json'; 
//i didn't create the file above since I wasn't able to find it in your repository. Maybe that's why it didn't work?

let app = express();

let predefinedSpec;

try {
    predefinedSpec = (JSON.parse(
        fs.readFileSync(openAPIFilePath, { encoding: "utf-8" })
    ));
} catch (e) {
    console.log(e.message);
}

handleResponses(app, {
    specOutputPath: openAPIFilePath,
    writeIntervalMs: 0,
    predefinedSpec: predefinedSpec ? () => predefinedSpec : undefined,
});

app.use(express.json());

app.post('/customer', (req, res)=> {
    try{
        const { name } = req.body;
        return res.status(200).send(`New costumer is called ${name}`);
    }catch (e){
        return res.status(400).send(e.message);
    }
});

module.exports = { 
    app,
    startServer: function startServer({
        portOverride = undefined,
    }) {
        const PORT = portOverride ?? process.env.PORT ?? 8000;
    
        /** serving */
        const server = app.listen(PORT, () => {
            console.log(`~ Server listening on PORT \`${PORT}\` @ NODE_ENV \`${process.env.NODE_ENV}\``);
        });    
        return server;
    }
};

handleRequests();
```


And then
sample.test.js

```
const request = require('supertest');
const { startServer } = require("./index");


const PORT = process.env.PORT || 8000;
const baseUrl = `http://localhost:${PORT}`;
const requestWrap = request(baseUrl);

describe("/customer API", () => {
  it("should fail if the students array file does not exist", async () => {
    try {
      const name = "Pedro";
      const res = await requestWrap
      .post(`/customer`)
      .send({
          name
      });

      expect(res.statusCode).toEqual(200);
      expect(res.text).toEqual(`New costumer is called ${name}`);
    } finally {
      //
    }
  });
});

```

I guess I'm missing something. One thing I guess should be there and isn't is something like this:

```
epxressOasGenerator.init(app, {
    "info": {
        "description": "My very nice customer api"
    },
},
'swagger.json');   
```

But since I didn't find this in your explanation, I didn't want to put without knowing the proper way to do it. Maybe that has something to do with why it failed?

Thank you a lot for your help!

**Comment by sarpik** [comment]
Alright, I realised that there are quite a few nuances, so I've created an example project with jest!

You can reach it here (before we merge it into master): https://github.com/mpashkovskiy/express-oas-generator/pull/53

And if you want to try it out:

```sh
git clone https://github.com/sarpik/express-oas-generator
cd express-oas-generator
git checkout sarpik/examples-with-jest
cd examples/with-jest
```

and see the README. Should definitely help!

**Comment by pedrokohler** [comment]
That's awesome @sarpik. Thank you very much.

It worked well here. I guess I only have a last question:

Is there a way to perserve the descriptions of the api and its methods? I ran some tests and every time it changed the file, the descriptions were reset.

**Comment by sarpik** [comment]
@pedrokohler cheers!

> Is there a way to perserve the descriptions of the api and its methods? I ran some tests and every time it changed the file, the descriptions were reset.

could you give a more concrete example and how could I re-produce it?

**Comment by pedrokohler** [comment]
Sure!

file.json
```
{
  "info": {
    "title": "with-jest",
    "version": "1.0.0",
    "license": {
      "name": "MIT"
    },
    "description": "An API for my classroom"
  },
  "paths": {
    "/api/v1/student": {
      "get": {
        "summary": "Method to get the nicest student of the class",
        "consumes": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "student": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number",
                      "example": 1337
                    },
                    "name": {
                      "type": "string",
                      "example": "Robert'); DROP TABLE Students;--"
                    }
                  }
                }
              }
            }
          }
        },
        "produces": [
          "application/json"
        ]
      }
    }
  },
  "swagger": "2.0",
  "schemes": [
    "http"
  ],
  "host": "localhost:5069"
}
```

I edited the file manually, changing the api description and the method summary.

After that I added another method to the api and created a test for it. It generated a new updated documentation, but the description and summary changes I did previously were lost:

```
{
  "info": {
    "title": "with-jest",
    "version": "1.0.0",
    "license": {
      "name": "MIT"
    },
    "description": "[Specification JSON](/api-spec)"
  },
  "paths": {
    "/api/v1/student": {
      "get": {
        "summary": "/api/v1/student",
        "consumes": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "student": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number",
                      "example": 1337
                    },
                    "name": {
                      "type": "string",
                      "example": "Robert'); DROP TABLE Students;--"
                    }
                  }
                }
              }
            }
          }
        },
        "produces": [
          "application/json"
        ]
      },
      "post": {
        "summary": "/api/v1/student",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "John"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "student": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number",
                      "example": 6449
                    },
                    "name": {
                      "type": "string",
                      "example": "John"
                    }
                  }
                },
                "success": {
                  "type": "boolean",
                  "example": true
                }
              }
            }
          }
        },
        "produces": [
          "application/json"
        ]
      }
    }
  },
  "swagger": "2.0",
  "schemes": [
    "http"
  ],
  "host": "localhost:5069"
}
```

Is there a way to preserve these changes?

Thanks!

**Comment by sarpik** [comment]
Ah gotcha.

Alright, since the documentation is being generated, it would be pretty fragile to also keep your customisations in the same file - you'd have to track it in source control to make sure things don't get lost.

Now, that may be a possible use case, but we have not implemented anything like it in `express-oas-generator` (yet?). I think we'd need some sort of a merge strategy that would persist the modifications.
Not sure if anyone can contribute this, but I've created an issue for it either 
way: https://github.com/mpashkovskiy/express-oas-generator/issues/54

---

I've actually wanted something similar, so for yet another work-around, you could explore what I did here:

https://github.com/sarpik/turbo-schedule/blob/83253ae70314790d76f7f2cfeb5ef9811503ae64/server/src/script/module/modifyGeneratedAPIDocs.ts

which I call from here: https://github.com/sarpik/turbo-schedule/blob/83253ae70314790d76f7f2cfeb5ef9811503ae64/server/src/script/module/generateOpenAPIDocs.ts

...buuuut it's pretty meh:D I'd love if anyone wanted to contribute to #54.

**Comment by mpashkovskiy** [comment]
@pedrokohler, @sarpik added comment in #54

**Comment by mpashkovskiy** [comment]
closing that one as we have more specific #54, feel free to reopen if needed

**Comment by muthu1712** [comment]
@sarpik I did try the same logic that you have explained - having a start server method and running it for tests.
But what happens now is, the server is now actually running and my tests are using that server, so the mocks i have setup in my test files are not being considered.

`const request = require('./supertest');

jest.mock('../src/helpers');
const { downloadFile } = require('../src/helpers');

const fileResponse = {
    ...expectedResponse...
  };
  
downloadFile.mockImplementation(() => Promise.resolve({ fileResponse }));

describe('File manager tests', () => {
  it('Should download file by name', async (done) => {
    const res = await request.get(`/directory/file/view?fileName=foo.pdf`);
    expect(res.statusCode).toEqual(200);
    expect(res.body).toEqual(fileResponse);
    done();
  });
}`

Instead of getting the mock response I've defined, the tests gets the actual response causing my tests to fail.
Please advise.

**Comment by sarpik** [comment]
@muthu1712 ugh I haven't used mocks in a while now, I'll take a look later hopefully, thanks for the fyi.

**Comment by muthu1712** [comment]
@sarpik 
I did came up with a workaround for working with mocks. Just wanted to share info here.


Instead of writing mocks in my tests directly, i had a mockFile written and inject that into my controller when running in test environment.

ActualMethodFile.js
````
const actualMethod = () => { // Actual Implementation Here // }
module.exports = actualMethod
````

MockMethodFile.js
````
const mockMethod = () => { // Mock Implementation/Mock return value // }
module.exports = mockMethod
````

MethodFile\index.js
````
const mockMethod = require('./MockMethodFile.js')
const actualMethod = require('./ActualMethodFile.js') 
const method = process.env.NODE_ENV === 'test' ? mockMethod : actualMethod
module.exports = method
````
