### ISSUE TITLE
Doesn't handle nested routers

### ISSUE THREAD

**Issue by williamoliveira** [mpashkovskiy/express-oas-generator#5]
It needs a recursive code [here](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L34)

[example](https://github.com/AlbertoFdzM/express-list-endpoints/blob/develop/src/index.js#L29)

**EDIT:** made it work in a fork [here](https://github.com/williamoliveira/express-oas-generator/commit/df9271013e22963d4e614901df8990f975e45ec9), I will not make a PR cause I copied some code from [express-list-endpoints](https://github.com/AlbertoFdzM/express-list-endpoints/blob/develop/src/index.js#L29) that I dont even know what it does :P

**Comment by mpashkovskiy** [comment]
Thanks William for reporting the bug and especially for pointing to express-list-endpoints. Will incorporate it in couple days and let you know when to update to newer version.

**Comment by mpashkovskiy** [comment]
Hm... It went much faster then I thought or I was just to excited about the opportunity to use express-list-endpoints. So could you try version 0.1.19 and let me know if I manage to fix the problem?

**Comment by williamoliveira** [comment]
Works great, thank you.
And glad the suggestion helped
