### ISSUE TITLE
The directory of the spec file is not ensured before trying to write the file

### ISSUE THREAD

**Issue by kiprasmel** [mpashkovskiy/express-oas-generator#51]
We'll need something like

```sh
npm i mkdirp
```

```js
const mkdirp = require('mkdirp');
const path = require('path');

const dir = path.parse(specOutputPath).dir
mkdirp.sync(dir);
```

**Comment by mpashkovskiy** [comment]
minor though good thing to have, PR?

**Comment by maxiejbe** [comment]
@kiprasmel I will implement the accepted answer: https://stackoverflow.com/questions/13542667/create-directory-when-writing-to-file-in-node-js 👍

**Comment by maxiejbe** [comment]
Done @kiprasmel @mpashkovskiy #91
