### ISSUE TITLE
[FR] Create an option to preserve the openAPI spec file instead of overwriting it

### ISSUE THREAD

**Issue by kiprasmel** [mpashkovskiy/express-oas-generator#52]
Originally from https://github.com/sarpik/turbo-schedule/issues/45

Work-around:

```diff
+const fs = require('fs')

/** handle the responses */
if (process.env.NODE_ENV !== 'production') {
  /** work-around - https://github.com/mpashkovskiy/express-oas-generator/issues/51 */
  mkdirp.sync(path.parse(openAPIFilePath).dir);

+ /** work-around - https://github.com/mpashkovskiy/express-oas-generator/issues/52 */
+ let predefinedSpec;

+ try {
+   predefinedSpec = JSON.parse(
+     fs.readFileSync(openAPIFilePath, { encoding: 'utf-8' })
+   );
+ } catch (e) {
+   //
+ }

  /** work-arounds done. Now handle responses - MUST be the FIRST middleware */
  handleResponses(app, {
    specOutputPath: openAPIFilePath,
    writeIntervalMs: 0,
+   predefinedSpec: predefinedSpec ? () => predefinedSpec : undefined,
  });
}
```

**Comment by mpashkovskiy** [comment]
looks like a good idea, could you create a PR if you have it in your fork?

**Comment by sarpik** [comment]
Yep, I have this work-around in my server and pretty sure I can port it to eoas-gen. Will do soon:)

**Comment by maidul98** [comment]
Hey! I was looking to do the same thing, where did you add code to do this?

**Comment by sarpik** [comment]
Hey @maidul98, the work-around is available above. As far as the feature request, I have not worked on it yet & it's free for grabs if anyone wants to:)

**Comment by mpashkovskiy** [comment]
Hey @maidul98 does the snippet from @kiprasmel work for you? It looks good to me so closing the ticket, if you need any assistance please reopen.

**Comment by maxiejbe** [comment]
I've just seen this issue on the example! Could you please reopen @kiprasmel?

**Comment by maidul98** [comment]
@maxiejbe did it not work for you?

**Comment by maxiejbe** [comment]
> @maxiejbe did it not work for you?

It works, but still a workaround. This should be handled internally.

**Comment by kiprasmel** [comment]
Yep, completely agree - we need to handle this internally.

**Comment by mpashkovskiy** [comment]
ok, reoping it

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy An approach to implement this feature would be to use `predefinedSpec` as `transformSpec`.

Always read `specOutputPath` to `spec` at the beginning of `handleResponses`. 
When serving, using `transformSpec` to either merge the objects or apply function.

Sounds good?

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy Guys I'll be sending a PR today/tomorrow along with #51 😄

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy there you go! #86
