### ISSUE TITLE
[FR] Merge/persist state of generated docs to allow customization without overriding it

### ISSUE THREAD

**Issue by kiprasmel** [mpashkovskiy/express-oas-generator#54]
Originally from https://github.com/mpashkovskiy/express-oas-generator/issues/49#issuecomment-629810963

**Comment by mpashkovskiy** [comment]
@pedrokohler, @sarpik there is a way to persist you descriptions and any other changes during runs. The second argument of `init()` method could be a callback function. Here is an example:

```javascript
generator.init(app, function(spec) {
    _.set(spec, 'info.title', 'New Title');
    _.set(spec, 'paths[\'/path\'].get.parameters[0].example', 2);
    return spec;
});
```

There are several ways to implement it:
* programmatically: just like in the example
* with use of JSONPatch: json patch file is stored separately in the repo and is used by callback function. there are some JS libraries simplifying JSON patching like http://jsonpatchjs.com/

**Comment by pedrokohler** [comment]
@mpashkovskiy you sould call this in the default export of the pacakge despite of if you're implementing the advanced way usage? Like that:

```
const generator = require('express-oas-generator');
const { handleResponses, handleRequests } = generator;

generator.init(app, function(spec) {
  _.set(spec, 'info.title', 'New Title');
  _.set(spec, 'paths[\'/path\'].get.parameters[0].example', 2);
  return spec;
});
```

Also, my linter complains about this _ out of nowhere. What is that supposed to be and where does it come from?

**Comment by sarpik** [comment]
I'm not sure if we've implemented this in the advanced usage example, will take a look soon.

the `_` is `lodash` -- you could instead just use

`spec.info.title = 'New Title'` etc.:D

**Comment by pedrokohler** [comment]
> the _ is lodash -- you could instead just use

@sarpik I mean, obviously! Sorry about that! LOL!

**Comment by sarpik** [comment]
Haha no problem stuff like this always happens:D

**Comment by mpashkovskiy** [comment]
@pedrokohler with advanced usage this is how it looks like:

```javascript
let app = express();
/** place handleResponses as the very first middleware */
expressOasGenerator.handleResponses(app, {
  predefinedSpec: function(spec) {
    _.set(spec, 'info.title', 'New Title');
    _.set(spec, 'paths[\'/path\'].get.parameters[0].example', 2);
    return spec;
  }
});

/** initialize your `app` and routes */

/** place handleRequests as the very last middleware */
expressOasGenerator.handleRequests();
app.listen(PORT);
```

**Comment by maidul98** [comment]
> @pedrokohler with advanced usage this is how it looks like:
> 
> ```js
> let app = express();
> /** place handleResponses as the very first middleware */
> expressOasGenerator.handleResponses(app, {
>   predefinedSpec: function(spec) {
>     _.set(spec, 'info.title', 'New Title');
>     _.set(spec, 'paths[\'/path\'].get.parameters[0].example', 2);
>     return spec;
>   }
> });
> 
> /** initialize your `app` and routes */
> 
> /** place handleRequests as the very last middleware */
> expressOasGenerator.handleRequests();
> app.listen(PORT);
> ```

Where do you specify where to save the file?

**Comment by mpashkovskiy** [comment]
I think this question is resolved. Isn't it? Feel free to reopen if need any assistance.
