### ISSUE TITLE
First request never generates response doc

### ISSUE THREAD

**Issue by jens-peterolsson** [mpashkovskiy/express-oas-generator#55]
The first request in my projects only creates documentation for the routes, not for the responses. When running the same request more than once, the response is added to the documentation.

(Tried experimenting with writeIntervalMs and other settings, but can't get it to work.)

I've created a test repo demonstrating the issue. This is extra bad since the best use case for express-oas-generator is to use it with unit tests, those promoting both TDD and swagger doc without having to do it manually with annotations etc.

Example repo:
https://github.com/jens-peterolsson/test-express-oas-generator

`npm start` then `http://localhost:5000/data`

or just

`npm test`

Spec is merged with swagger.json.

**Comment by sarpik** [comment]
Related / duplicate: https://github.com/mpashkovskiy/express-oas-generator/issues/50 (it's not the first request that gets ignored, but the last one).

**Comment by jens-peterolsson** [comment]
> Related / duplicate: #50 (it's not the first request that gets ignored, but the last one).

Could be related but I don't think it's a duplicate since in example repo the second request is the one that produces the response doc.

**Comment by maxiejbe** [comment]
@jens-peterolsson @kiprasmel Just cloned the test project, pointed express-oas-generator to my fork branch (`git://github.com/maxiejbe/express-oas-generator.git#fix/#50-unhandled-first-last-req-res`) and it's now working. Addressed by https://github.com/mpashkovskiy/express-oas-generator/pull/73

**Comment by mpashkovskiy** [comment]
I think it is fixed now as #73 is merged. Please confirm.
