### ISSUE TITLE
Feature request: Possibility to specify baseUrlPath in the code

### ISSUE THREAD

**Issue by adams-family** [mpashkovskiy/express-oas-generator#56]
First of all, thanks for this GREAT tool! I've alrady given you a star and promoted the tool on stackoverflow. (This was not related to the feature request)

I appreciate the possibility to specify a `baseUrlPath` in the `package.json` file.

It would be useful, however, if I could drive the base URL using an environment variable during Docker deployments.

My suggestion is something similar as:

```javascript
let app = express();
expressOasGenerator.init(app, {
   baseUrlPath: process.env.BASE_URL
});
```

Any suggestions / objections? Thanks!

**Comment by adams-family** [comment]
I think I might have resolved this myself. I found this workaround and it works very well for me:

```javascript
expressOasGenerator.init(app, function(spec) {
	spec.basePath = process.env.BASE_URL || '';
    return spec;
});
```

Please feel free to close this ticket if you think that this is a good solution.

**Comment by mpashkovskiy** [comment]
Actually there is a [possibility to specify `baseUrlPath`](https://github.com/mpashkovskiy/express-oas-generator#optional-additions-to-your-packagejson) but looks like it is not propagated to the actual specification [here](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L82).
Would you, @adams-family , be so kind to add a line, check tests and create a PR?

**Comment by mpashkovskiy** [comment]
And thank you for promotion!

**Comment by mpashkovskiy** [comment]
Hi @adams-family, I implemented the "feature" could you try it and let me know if it works as expected? I can publish new version after it.

**Comment by adams-family** [comment]
Hi @mpashkovskiy - I'm sorry I missed your original message a month ago :(

In my case, specifying the baseUrlPath in the `package.json` is not ideal because I'm running a monorepo (nrwl.io) and I have multiple NodeJS project covered by one `package.json`. Each project is deployed to a different `baseUrl` on the same host, such as:

- /public-api
- /admin-api

I am however happy with the workaround I found (above) because this way I can specify a different baseUrl per each project:

```js
expressOasGenerator.init(app, function(spec) {
    spec.basePath = process.env.BASE_URL || '';
    return spec;
});
```

Is there anything else I can test for you?

**Comment by mpashkovskiy** [comment]
I see. Indeed my implementation won't be useful for you. Thanks for explanation, no actions needed then.

**Comment by adams-family** [comment]
No worries, thanks again for this great tool!
