### ISSUE TITLE
Doesn't read body parameters

### ISSUE THREAD

**Issue by maidul98** [mpashkovskiy/express-oas-generator#58]
Is there any way to get the body parameters to get into the api doc automatically?

**Comment by sarpik** [comment]
you mean the request's body, like some JSON data?

If so, you'd need to make requests with the data in order to include them. I myself have automatic unit tests to do just that: https://github.com/sarpik/turbo-schedule/tree/master/server/src/test

**Comment by maidul98** [comment]
Yes, i ment raw json data in the body. I have made requests with raw json in body, but they don't seem to appear in the docs. Am i not sending the data correctly?

**Comment by mpashkovskiy** [comment]
It is possible that the midlewares chain is broken somewhere, could you please check [this comment](https://github.com/mpashkovskiy/express-oas-generator/issues/24#issuecomment-518607492).

Please reopen the issue if it doesn't solve the problem.
