### ISSUE TITLE
Automatically load & save api-spec.json

### ISSUE THREAD

**Issue by anodynos** [mpashkovskiy/express-oas-generator#6]
It would be great if we had a config as 3rd param, where we can specify various settings, one of them being the path of the currently generated spec, so it can be loaded and saved. 

Right now we're using it as: 
```
expressOasGenerator.init(expressApp, require('../api-docs/api-spec.json'))
``` 
which means we have to manually update it via copy-paste when it changes. 

With the new proposal it would look similar to: 

```
expressOasGenerator.init(expressApp, null, {
  currentSpec: '../api-docs/api-spec.json', // auto loads it
  autoSave: true // or it can be a `_.debounce` number, defaulting to 1000ms
)})
```

**Comment by mpashkovskiy** [comment]
Hi Angelos.

I have some doubts if it is right approach. Most of the time I worked with microservices running on several nodes behind a load balancer and usually you don't have access to those nodes (you don't need it) and they are dropped by every deploy triggered by merge/commit to the VCS repo. Because of it it sounds a bit wrong to save spec locally.
Instead I would suggest configure a job on CI server (for example on Jenkins) that every hour would run something like:

```
cd your-app-repo-root/api-docs
wget -O api-spec.json http://host:port/api-spec
git commit -a -m "updated REST API spec"
git push
```

What do you think?

**Comment by anodynos** [comment]
Yeah, that could work also, for production. But our intention is to have it **only** on local dev & perhaps staging, that's where the auto-save would be useful.

**Comment by Asafb26** [comment]
+1 for this. you did an awesome work btw 😀

**Comment by mpashkovskiy** [comment]
OK will add this feature.

**Comment by AliMol** [comment]
Hi mpashkovskiy
Has this feature been added to the repo ? I also need to save this json on my local .

Thanks in advance mpashkovskiy ...

**Comment by mpashkovskiy** [comment]
Unfortunately it hasn't been implemented yet.
Looks like I really have to find the time for it as several people want it

**Comment by ccope** [comment]
I needed this myself and hacked in a simple call to fs.writeFileSync with a JSON encoding of the spec right after this line: https://github.com/mpashkovskiy/express-oas-generator/blob/5fa0b2103d9e330270827ac0c5f08e615a5a2048/index.js#L141

There's probably a more elegant way to do this but it's fine in my dev environment.

**Comment by mpashkovskiy** [comment]
Added support for storing files, please check if it work for you guys (see README).
Don't forget to switch to version 1.0.1
