### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by mpashkovskiy** [mpashkovskiy/express-oas-generator#70]
They are shutting down travis-ci.org and thus all the projects have to migrate to travis-ci.com.

From official email:
> We encourage you to migrate your existing repositories that are currently on travis-ci.org over to travis-ci.com as soon as possible, enabling you to identify any additional changes required to your code or configuration well in advance of the December 31st deadline. We’ve documented everything you need to know in order to migrate your repositories, and of course, you can reach out on the community forum for any additional help.

**Comment by kiprasmel** [comment]
oh damn that's a shame - a lot of people will have to waste time on this..

**Comment by matveypashkovskiy** [comment]
Looks like it is time to migrate and I think it is better to GitHub Actions. Will do it. And also let's make some rules about commit messages.

**Comment by mpashkovskiy** [comment]
somehow CI still works, so the ticket is irrelevant
