### ISSUE TITLE
 About the requesting body 

### ISSUE THREAD

**Issue by eeswq** [mpashkovskiy/express-oas-generator#74]
express-oas-generator is the salvation of my situation right now. Thank you 
I have a question.
Is there a way to request a definition for the request body? or
Is there a way to predefine the response?
Or is there any possibility to add to that function?

Thank you again

**Comment by mpashkovskiy** [comment]
Thanks, @eeswq for kind words.

> Is there a way to request a definition for the request body?

Do yo mean a definition of the request from OpenAPI spec? There is no separate path to get it, the only way it is possible now is to get the full OpenAPI spec from `/api-spec/` and access the needed section programmaticaly

> Is there a way to predefine the response?

It is possible to provide a callback to `init()`/`handleResponses ()` method and transform the spec before serving it. See README.md for more info. Example:
```javascript
generator.init(app, function(spec) {
    _.set(spec, 'info.title', 'New Title');
    _.set(spec, 'paths[\'/path\'].get.parameters[0].example', 2);
    return spec;
});
```

**Comment by eeswq** [comment]
Thanks for the quick reply. Have a nice day! and
Thanks again for making a great program

**Comment by arunkoshi** [comment]
A related question, is there a way to **not** generate `host`.  I tried the following but i still get the host generated as `localhost:8080`

```
generator.handleResponses(app, {
    predefinedSpec: spec => {
      _.set(spec, "info.title", "Test API");
      _.set(spec, "info.description", "Test Description");
      _.set(spec, "host", "");
      return spec;
    },
    writeIntervalMs: 3000,
    specOutputPath: "./server/swagger_admin.json"
  });
```
