### ISSUE TITLE
Prevent host and schemes fields from getting generated

### ISSUE THREAD

**Issue by arunkoshi** [mpashkovskiy/express-oas-generator#77]
Thanks for this awesome module.

Is there a way to **not** generate `host` and `schemes` in the spec? 

We are trying to generate the spec during the build/test phase, package and use it in all environments. But because of the generated `host` value, swagger does not seem to pick the url dynamically (based on the environment url where it is served from).

I tried the following for removing the `host` but i still get the host generated as `localhost:8080`.

```
generator.handleResponses(app, {
    predefinedSpec: spec => {
      _.set(spec, "info.title", "Test API");
      _.set(spec, "info.description", "Test Description");
      _.set(spec, "host", "");
      return spec;
    },
    writeIntervalMs: 3000,
    specOutputPath: "./server/swagger_admin.json"
  });
```

**Comment by mpashkovskiy** [comment]
It is interesting, I'm trying to reproduce the issue by running "node server_basic.js" and I don't see host property in the schema. How do you get it?

**Comment by mpashkovskiy** [comment]
which version of the module do you use?

**Comment by mpashkovskiy** [comment]
Ok I managed to reproduce it. Use `_.set(spec, 'host', undefined);` to remove the field.
