### ISSUE TITLE
Question on request body

### ISSUE THREAD

**Issue by matteolc** [mpashkovskiy/express-oas-generator#82]
Hi

Running the examples in this repo (server_basic/advanced) i was expecting the request body params to get documented in the auto-generated json however this does not appear to happen. Is this the expected behaviour?

I can see that the body processor correctly recognizes the body, however it doesn't appear to be added to the file?
Am i missing something?

Thanks!

**Comment by matteolc** [comment]
Hi
I patched with changes from https://github.com/maxiejbe/express-oas-generator and now it works as expected.
Best

**Comment by matveypashkovskiy** [comment]
Hi @matteolc could you please elaborate a bit? What didn't you see in API spec initially and what did appear when you patched it with @maxiejbe's fork?

**Comment by matveypashkovskiy** [comment]
is it related to https://github.com/mpashkovskiy/express-oas-generator/pull/73 ?

**Comment by lucasvillaverde** [comment]
> is it related to #73 ?

Think it is. It was happening to me until i read this issue. Thx.

**Comment by maxiejbe** [comment]
Yes, I'm experiencing the same issue @matveypashkovskiy, I'm even using my fork for our projects since then.
If you agree, lets give priority to that PR.
Thanks!

**Comment by mpashkovskiy** [comment]
Thanks @maxiejbe for clarification, PR is merged and the new version is published. Thanks everyone for raising the issue. Please check if it works.

**Comment by mpashkovskiy** [comment]
feel free to reopen it

**Comment by matveypashkovskiy** [comment]
@maxiejbe, @matteolc, @lucasvillaverde could you please confirm that v1.0.32 works for you (solves the issue)?

**Comment by maxiejbe** [comment]
> @maxiejbe, @matteolc, @lucasvillaverde could you please confirm that v1.0.32 works for you (solves the issue)?

Working like a charm in example project! I've even removed the last call to update the docs on each test suite as @kiprasmel suggested. Take a look at https://github.com/CodeaIT/men-challenge/pull/18
