### ISSUE TITLE
parameters and body not documented when not calling to next function

### ISSUE THREAD

**Issue by Asafb26** [mpashkovskiy/express-oas-generator#9]
considering this example (taken from express site):
```
const express = require('express')
const app = express()

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```

the generator will parse the uri but not the parameters and body unless we explicitly call to next: 

```
const express = require('express')
const app = express()

app.get('/', (req, res, next) => {res.send('Hello World!')); next();}

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```

I know that this route not have any use of params and body, this is only for the example 😄

**Comment by mpashkovskiy** [comment]
That is true, you have to call next(). It is also discussed in #4 
The reason behind that is following: request/response parsing middleware need to have request body parsed so it should be placed after [body-parser](https://github.com/expressjs/body-parser). It is hard to put it right after this middleware so we put at the very end.

There is [cool approach](https://github.com/newrelic/node-newrelic/blob/master/lib/shimmer.js#L311) used by new relic agent but implementing this will explode the scope of this module.

**Comment by Asafb26** [comment]
Thanks!
so now with calling to next function, routes pattern like this senario result with exception for the uri `/api/albums/artwork`:
`Error: Can't set headers after they are sent.`
```
app.get('/api/albums/artwork', routes.albums.getAlbumArtwork);
app.get('/api/albums/:id', routes.albums.getAlbum);
```

the next function calls to the next route /:id which is trying to call res.json for the second time.

**Comment by mpashkovskiy** [comment]
Could you please elaborate a bit more? What do you have in `routes.albums.getAlbumArtwork`? How can I reproduce it?

**Comment by Asafb26** [comment]
Sure, take a look at a this example:
```
router.route('/foo/stranger')
        .get(function (req, res, next) {
            res.json({message: 'hello stranger'});
            return next();
        });
    router.route('/foo/:name')
        .get(function (req, res, next) {
            res.json({message: 'hello ' + req.params.name});
            return next();
        });
```
for `http://localhost:8080/foo/stranger` route, i get exception: `Error: Can't set headers after they are sent.`
this is not happens when i remove the invocation of next() function

**Comment by mpashkovskiy** [comment]
Thanks for patience. I managed to reproduce the bug. It is related to router configuration please see develop branch [server.js file](https://github.com/mpashkovskiy/express-oas-generator/commit/43032257e577d042452bb0770a5cf169d6d7903f)

So if you run `node server.js` and point your browser to http://localhost:8080/foo/stranger you will see in the console

```
calling /foo/stranger
calling /foo/:name
```
Which actually means that both handlers are executed. Second `res.json()` tries to set at least `Content-Type` header and fails with the exception you mentioned.

I would suggest to change paths or combine two handlers into one.

Please let me know if it solves your problem.

**Comment by Asafb26** [comment]
Thanks!  I ended this issue by checking the existing of req.params.name in the second route, that's keeps the uniqueness of each route
