### ISSUE TITLE
/api-docs route not found

### ISSUE THREAD

**Issue by samarincred** [mpashkovskiy/express-oas-generator#93]
I tried both the advanced and basic usage patterns. However, api-docs/ path does not seem to be recognised by express. I tried seeing all the routes of express by running DEBUG=express:* npm start . The screenshot is below. It seems that the express:router:route debug output for the **get**  api-docs is missing. What might be happening here?

<img width="549" alt="Screenshot 2021-06-07 at 7 28 32 AM" src="https://user-images.githubusercontent.com/84518503/120949523-5911e700-c762-11eb-9315-0868dc1f441d.png">

**Comment by maxiejbe** [comment]
@samarincred Would you send a minimal reproduction example?

`/api-docs` is appended to your baseUrl. Maybe you're using a trailing `/api`, resulting in `/api/api-docs`? 

Btw, please use recommended advanced usage, basic usage is about to be deprecated.

**Comment by maxiejbe** [comment]
Hi @samarincred, is this resolved? If so, can we close the issue?

**Comment by mpashkovskiy** [comment]
Closing the issue. Feel free to reopen if there are still questions.
