### ISSUE TITLE
Parameters and responses still not documented

### ISSUE THREAD

**Issue by LanderMalta** [mpashkovskiy/express-oas-generator#94]
hi guys, how are you?

thanks for the library, i added it in my app and i am using the latest published version `1.0.38`, but the parameters and responses are not documented yet.

I took a look at all the related issues that were reported about, like #24 , #50, #55, #73 and applied the changes that were recommended, but I still couldn't get it to work. :cry: 

what i tried:
-> I added `next()` and `next(err)` at the end of all my handles.
-> I'm using `advanced usage` with `handleResponses(app, {})` at the beginning and `handleRequests()` at the end of my root file.
-> I set the `writeIntervalMs = 0` parameter.
-> I set the `mongooseModels = mongoose.modelNames()` parameter. 

I made changes to the same example as issue #24 and the documentation looks like this:
![image](https://user-images.githubusercontent.com/3339092/121202180-78387380-c84b-11eb-9858-8641783f966b.png)

here is the code
[books_example.zip](https://github.com/mpashkovskiy/express-oas-generator/files/6617297/books_example.zip)

**Comment by LanderMalta** [comment]
Thanks for the reply @maxiejbe 
I called the endpoint with http client after starting the server and the request/response was documented successfully! :smile:  thank you so much! and thank you to for the tip for RECREATE and PRESERVE 
the spec file.

On the other hand I need to provide the swagger along with my api, and making all http calls at each start would be unfeasible.
I tried to create the tests and run them before running the application, but does not worked and request/response was not documented. So, what would be the best way to write the tests, or even better, what would be the best way to provide the swagger with the request/response along with the running application?

**Comment by LanderMalta** [comment]
here is the code with tests
[books_example.zip](https://github.com/mpashkovskiy/express-oas-generator/files/6621520/books_example.zip)

**Comment by maxiejbe** [comment]
Tests is a pretty good choice.
Your example is not working because you removed `specOutputPath: "./api-docs.json"` from `handleResponses` options. 
By default it keeps the spec in memory, so if you restart the app it's not persisted in disk. We were planning to persist in a default output path.

If you go with tests, rollback to `specOutputFileBehavior: SPEC_OUTPUT_FILE_BEHAVIOR.RECREATE` so you always have the latest docs after running the test suite.

Let me know if we can close the issue 😄

**Comment by LanderMalta** [comment]
Thank you very much @maxiejbe  for the explanation!. Your example was perfect to solve the doubt I had.
We can close the issue :pray: :smile:

**Comment by mannutech** [comment]
How to generate descriptions and explainers for Swagger docs?
