### ISSUE TITLE
typescript as dependency necessary?

### ISSUE THREAD

**Issue by yss14** [mpashkovskiy/express-oas-generator#95]
Is it necessary to specify typescript as `dependency` and not as `devDependency`?

We are using `typescript@4` and when installing `express-oas-generator` it installs a second typescript instance, and for some reason breaks our tsc builds.

**Comment by kiprasmel** [comment]
Heyo, last time we discussed this when we introduced typescript's type definitions - see https://github.com/mpashkovskiy/express-oas-generator/pull/43#issuecomment-554895376

Not sure if it's still the case - we could try to make it a dev dependency and see if the mentioned scenario, as well as the normal ones, do not break. /cc @mpashkovskiy

**Comment by mpashkovskiy** [comment]
Looks like nobody had time to test it, @yss14 would you try @kiprasmel suggestion and get back with the result? Or should we close the issue?

**Comment by yss14** [comment]
@mpashkovskiy Thanks for the reply, I guess we can close this issue since I moved my job in the meantime and `express-oas-generator` is our of stack.
